tokenizer:
  _component_: torchtune.models.gemma.gemma_tokenizer
  path: .local/ckpts/gemma-2b/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: /mnt/scratch/xiayao/projects/fmsys/mixtera/.cache/datasets/prepared/ni_train_mix1_0.1.jsonl
  conversation_style: "openai"
  max_seq_len: 2048
  chat_format: torchtune.data.GemmaFormat
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.gemma.gemma_2b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: .local/ckpts/gemma-2b
  checkpoint_files: [
    "model-00001-of-00002.safetensors",
    "model-00002-of-00002.safetensors"
  ]
  recipe_checkpoint: null
  output_dir: .local/ckpts/tuned/gemma-2b-mixtera-v2/
  model_type: GEMMA
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 4
epochs: 1

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  foreach: False

loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 16
optimizer_in_bwd: False
compile: True

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: False

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.WandBLogger
  project: mixtera
output_dir: .local/ckpts/tuned/gemma-2b-mixtera-v2/
log_every_n_steps: 1
log_peak_memory_stats: False
checkpoint_every_n_steps: 1000