tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: .local/ckpts/meta-llama-3-8b-instruct/original/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: .local/datasets/sft.jsonl
  conversation_style: "openai"
  max_seq_len: 4096
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: .local/ckpts/meta-llama-3-8b-instruct/original
  checkpoint_files: [
    consolidated.00.pth
  ]
  recipe_checkpoint: null
  output_dir: .local/ckpts/tuned/llama-3-mixtera-v1/
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 4
epochs: 1

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  foreach: False

loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 16


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.WandBLogger
  project: mixtera
output_dir: .local/ckpts/tuned/llama-3-mixtera-v1/
log_every_n_steps: 1
log_peak_memory_stats: False
